language: node_js
node_js:
  - "8"

script:
  npm run build

before_install:
  - npm install

after_script:
  - cd dist
  - git init
  - git config user.name "hihjdotcn"
  - git config user.email "miaojihj@outlook.com"
  - git add -A
  - git commit -m 'deploy'
  - git push -f git@github.com:<USERNAME>/<REPO>.git master:master

