language: node_js
node_js:
  - "8"

cache:
  directories:
    - node_modules

script:
  npm run build

before_install:
  - npm install

after_script:
  - cd dist
  - git init
  - git config user.name "hihjdotcn"
  - git config user.email "miaojihj@outlook.com"
  - git add -A
  - git commit -m "deploy"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}"

master: gh-pages

branches:
  only:
    - master

env:
 global:
   - GH_REF: github.com/hihjdotcn/hihjdotcn.github.io.git
